Form page
MahmoudBakr23/Displaying-and-Inputting-Data-Project pull request #1
Opened 2020-06-03 12:31 UTC by somoye123

At HTML changes:
- Adding form, fieldset, labels, inputs, submit button, and the footer tags.
At CSS changes:
1. styling the form tag including:
2. the fieldset section
3. the labels and inputs
4. the footer section
To be as the given webpage for the project

2020-06-03 13:05 UTC, HADDADSOHAIB requested changes
> ### Pull Request under the review by Sohaib Haddad. (TSE)
### Change Required :recycle: 

### Hello @somoye123  and @MahmoudBakr23   :handshake: 

### Good job so far :clap:  your project is looking good :medal_sports: 

### there are still some changes to get the project approved :point_down:

- In your Readme file there is non link to the live demo, please use http://raw.githack.com/ and update your readme file.
- The project should have a sign-in button:
##### Sign In Button
- [ ] It has a Sign In button at the top right corner ([link to page](https://accounts.intuit.com/signup.html))

Original:
![Screenshot from 2020-06-03 13-12-40](https://user-images.githubusercontent.com/26064042/83635394-0ffde480-a59c-11ea-84d3-0da99619f056.png)
Your project:
![Screenshot from 2020-06-03 13-46-53](https://user-images.githubusercontent.com/26064042/83638197-b77d1600-a5a0-11ea-8d82-ac98b75909f5.png)

- The page should have the intuit logo and products:
##### Intuit logo
- [ ] It shows the Intuit logo above the form ([link to page](https://accounts.intuit.com/signup.html))
- [ ] The intuit logo is an embedded image that is horizontally centered ([link to page](https://accounts.intuit.com/signup.html))

##### Intuit products
- [ ] The products row is under the Intuit logo and above the form ([link to page](https://accounts.intuit.com/signup.html))
- [ ] It shows the Mint logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
- [ ] It shows the Quickbooks logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
- [ ] It shows the Turbotax logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))

Original:
![Screenshot from 2020-06-03 13-15-02](https://user-images.githubusercontent.com/26064042/83635586-64a15f80-a59c-11ea-8da6-249eb38df5aa.png)
Your Project:
![Screenshot from 2020-06-03 13-46-53](https://user-images.githubusercontent.com/26064042/83638307-df6c7980-a5a0-11ea-8368-07d5683950b5.png)
- Having a footer is required:
##### Footer
- [ ] It contains copyright and address information ([link to page](https://accounts.intuit.com/signup.html))
Original:
![Screenshot from 2020-06-03 13-21-57](https://user-images.githubusercontent.com/26064042/83636144-5d2e8600-a59d-11ea-9bf3-64219eec7931.png)
Your Project: You don't have a footer.
### Check the comments for more details.
### Please implement the required changes and ask for another code review.

2020-06-04 00:08 UTC, HADDADSOHAIB requested changes
> ### Pull Request under the review by Sohaib Haddad. (TSE)
### Change Required :recycle: 

### Hello @somoye123  and @MahmoudBakr23   :handshake: 

### Good job so far :clap:  you implemented what I requested earlier and your project is looking good :medal_sports: 

### there are still some changes that come up to get the project approved :point_down:
- Always passe the HTML file through the validators before a pull request:
![Screenshot from 2020-06-04 01-03-33](https://user-images.githubusercontent.com/26064042/83700633-40c33580-a5ff-11ea-8083-6be30d54caf9.png)
Please fix these validations.
- there are some issues with the images:
your project:
![Screenshot from 2020-06-04 01-04-21](https://user-images.githubusercontent.com/26064042/83700694-65b7a880-a5ff-11ea-966e-fdf1f2e27ae0.png)
Check the comment I will add some suggestions on how to fix the images.
## please implement the changes and ask for another code review. :+1:

2020-06-04 00:12 UTC, HADDADSOHAIB commented on index.html
> +      <li><img src="/images/png-transparent-turbotax-computer-software-tax-return-intuit-type-miscellaneous-company-trademark-removebg-preview.png"></li> <p>turbotax</p>
Use an absolute path in the src attribute, it should be src="**.**/images/.......".

2020-06-04 09:56 UTC, andresporras commented
### **Pull Request Under Review By Oscar Russi (TSE)**

2020-06-04 09:57 UTC, andresporras requested changes
### Status: Change Required :recycle:
**Hello @somoye123 and @MahmoudBakr23** 
You did a great implementing some improvements, your images now have an absolute path, your page looks really close to the original  :clap:
There are still some improvements to do:

- [ ]  Check HTML markup with this validator https://validator.w3.org/#validate_by_upload

By now the validator shows some errors in your code.

### OPTIONAL

- [ ] it's recommended to use the main tag for the dominant content of the body of the document
- [ ] it's recommended to use nav tag for the major navigation links

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-06-04 10:21 UTC, somoye123 commented
We used the validator and we found no errors.
Please check the index.html file within the repo directory instead of the live demo

![Screenshot (181)](https://user-images.githubusercontent.com/41391263/83745396-57bf5300-a612-11ea-892b-aafb226f1e3d.png)

2020-06-04 10:24 UTC, somoye123 commented
@andresporras

2020-06-05 01:06 UTC, lucasmazo32 approved these changes
# Project approved :rocket:

#### Great job!

#### Your project looks great!

### You can go ahead and merge this pull request!

### Happy coding! :computer:

## Lucas Mazo

2020-06-05 01:37 UTC, merged